import type { ChapterType } from "@/lib/visual-types";

export const SAMPLE_TEXTS: Record<ChapterType, string> = {
  "opportunity-validation": `Opportunity Validation: Mid-Market Property Management Software

Overview: The core opportunity targets mid-market commercial property managers (50-500 units) who lack integrated software for tenant screening, lease management, and maintenance coordination. These managers juggle 3-4 separate tools, leading to data silos, missed renewal windows, and slow maintenance response times averaging 72 hours. Revenue shortfall from tenant turnover averages $3,500 per unit. Pipeline drag from manual processes costs an estimated $718,560 annually across a typical 200-unit portfolio. Queue attrition rate sits at 15% due to delayed maintenance responses. The urgency window is 18-24 months before AppFolio's AI capabilities close the differentiation gap.

Problem and Customer Definition: Regional property management companies with $5M-$50M in assets under management face a revenue floor collapse. Before digital consolidation, average revenue per unit was $284 per kW-year. Current fragmented tool approaches have driven this down to $140 per kW-year. The core problem is fragmented operations creating invisible revenue leakage. The primary customer is the operations director at mid-market property firms. The key pain point is tenant turnover cost averaging $3,500 per unit. The trigger event is typically a failed maintenance request escalating to lease non-renewal. The business consequence is a 50% drop in per-unit revenue and accelerating churn.

Demand Signals: Search interest for property management automation increased 340% since 2023. Three major industry conferences added dedicated PropTech tracks in 2024. Direct conversations with 28 property managers found that 22 expressed willingness to pay $15-25 per unit per month. However, stated willingness to pay has not been validated through actual purchase commitments. No signed letters of intent or pilot agreements exist yet. The evidence chain shows strong early signals but a critical gap between stated intent and commercial commitment.

Current Solution and Market Gap: Spreadsheet-based tracking, used by 60% of the target segment, solves basic record-keeping but fails at cross-functional visibility and predictive alerts. Yardi Voyager provides comprehensive features but fails at mid-market affordability and implementation simplicity. Cobbled SaaS stacks such as AppFolio plus separate maintenance tools solve individual workflows but fail at data integration and predictive capabilities. Revenue gap analysis shows spreadsheet users losing $349,300 per year in preventable turnover, Yardi users losing $180,000 per year in overpayment and underutilisation, and SaaS stack users losing $245,000 per year in integration friction.

Customer Fundamentals: The buying process involves the Operations Director identifying the need, the CFO approving budget with a six-month ROI threshold, and the IT Director reviewing security and integration. Budget cycles are annual with Q4 decision-making for January implementation. Typical evaluation windows run 4-8 weeks. The six-month ROI requirement is the primary gate.

Risks and Next Steps: Risk 1: no commercial validation exists beyond stated interest, probability high, severity high. Mitigation: secure 3 paid letters of intent within 90 days. Risk 2: AppFolio could add predictive maintenance within 12 months, probability medium, severity high. Mitigation: accelerate differentiation through proprietary maintenance data models. Risk 3: budget freezes in the target segment due to interest rate pressure, probability medium, severity medium. Mitigation: position the product as a cost-saving tool with guaranteed ROI timelines. Risk 4: integration complexity with legacy accounting systems is underestimated, probability low, severity high. Mitigation: build QuickBooks and Sage connectors as launch requirements. Risk 5: customer acquisition cost exceeds the $4,500 per account target, probability medium, severity medium. Mitigation: partner with property management associations for channel access.`,
  "market-research": `Market Research: US Commercial Property Management Software

Overview: The US commercial property management software market is a $4.2B market growing at 11.3% CAGR. The market is moderately concentrated with structural tailwinds from digital transformation and regulatory compliance. The main constraint is customer acquisition cost in a market where switching costs create inertia. New entrants need a clear wedge into the mid-market segment where fragmentation creates openings.

Market Sizing and Structure: TAM is $4.2B across all commercial property management software in the US and Canada. SAM is $1.8B for mid-market operators managing 50-500 units. SOM is $45M in years 1-3, based on capturing 2.5% of SAM. Geographic concentration is highest in Sun Belt states, with Texas at 18%, Florida at 15%, and Arizona at 9%. The top 20 property management firms control 25% of mid-market units. Market structure is fragmented in mid-market, with no player above 12% share, versus concentrated at enterprise level where the top 5 hold 55%.

Trends and Growth: AI-driven predictive maintenance adoption is growing 28% annually. Regulatory requirements for energy efficiency reporting are expanding. Consolidation among mid-tier firms is accelerating. The remote property management shift is now permanent and digital-first operations are table stakes rather than a differentiator.

Value Chain and Competitive Structure: The value chain flows from Property Acquisition and Setup through Tenant Acquisition and Onboarding to Ongoing Management and Maintenance to Financial Reporting and Distribution. The highest-margin activities sit in Ongoing Management where recurring SaaS revenue models dominate. Tenant acquisition is becoming commoditised. Financial reporting is dominated by accounting integrations. The whitespace is in predictive operations connecting Ongoing Management to Financial Reporting with real-time analytics.

Buying Cycle and Commercial Dynamics: Adoption stage is early majority. Typical buyer motion is inbound-led evaluation. Buying cycles run 3-6 months for mid-market deals. Main gating events are CFO sign-off above $1,000 per month and IT security review. Common failure points are failed integration demos and inability to demonstrate ROI within six months. Purchase format is annual SaaS subscription. Unit spend is $800-$2,400 per month and portfolio spend is $15-$25 per unit per month.

Entry Conditions and Adoption Constraints: Integration with QuickBooks or Sage is critical because 70% of mid-market firms use one of these systems. A mobile-first maintenance workflow is required. Customer acquisition cost averages $4,500 per account. The minimum viable feature set must include lease management, maintenance ticketing, and financial reporting. Data migration from legacy systems is the primary adoption friction point.

Risks and Next Steps: Risk 1: market growth concentrates in segments we cannot reach initially, probability medium, severity medium. Risk 2: pricing pressure from AppFolio's low price point, probability high, severity medium. Risk 3: regulatory fragmentation increases development costs, probability medium, severity low. Risk 4: customer acquisition costs exceed the $4,500 target, probability medium, severity high. Risk 5: integration complexity delays time to market, probability low, severity high.`,
  "competitive-analysis": `Competitive Analysis: Mid-Market Property Management Software

Overview: The competitive field is structured in three tiers: enterprise incumbents such as Yardi and MRI, mid-market specialists such as AppFolio and Buildium, and vertical-focused startups such as Latchel and Property Meld. The market is in a growth and displacement phase where competitors primarily win against manual processes rather than against each other. The company occupies a potential sweet spot in predictive mid-market operations, but the window for establishing position is 18-24 months before AppFolio's AI capabilities mature.

Competitive Landscape Overview: AppFolio has 28,000 or more customers with 22% year-over-year growth. Strengths include a modern UI, strong accounting integration, and brand awareness. Weaknesses include limited predictive maintenance and a one-size-fits-all approach. Threat level is high. Buildium serves 15,000 or more customers with strong residential depth but weak commercial features. Threat level is moderate. Yardi Voyager holds 35% of the enterprise market with comprehensive features but struggles with mid-market adoption due to complexity and cost. Threat level is low to medium. Latchel and Property Meld are maintenance-focused specialists with strong workflow depth but narrow scope. Threat level is low.

Market Position and Share Dynamics: AppFolio holds approximately 12% of mid-market share and is gaining 3-4 percentage points annually. Buildium holds 8% and is flat. Yardi Breeze holds 3% and is growing slowly. Others collectively hold 77%. Most growth is displacing spreadsheet workflows rather than taking share from software incumbents.

Defensibility and Moat Architecture: The potential moat has three layers. First is predictive maintenance algorithms that no mid-market competitor currently offers. Second is integration depth with mid-market accounting systems, which creates switching costs. Third is contractor marketplace network effects that strengthen with usage density. Switching costs also come from data lock-in, workflow dependency, and painful integration replacement.

Differentiation and Right to Win: Predictive maintenance is the core differentiated capability. A purpose-built mid-market product matters because enterprise tools are over-complex and over-priced. Integration depth with mid-market accounting is mandatory because it underpins retention. Mobile-first maintenance is table stakes. Price-value ratio is competitive at $15-$25 per unit per month if predictive capabilities are demonstrably better.

Risk and Fragility: AppFolio adds predictive features after its 2024 AI startup acquisition, probability medium, severity high. Yardi Breeze improves UX and moves downmarket, probability low, severity medium. New entrants from adjacent categories expand scope, probability medium, severity medium. Customer concentration creates revenue fragility, probability medium, severity high. Talent shortages in AI and ML engineering slow delivery, probability high, severity medium.`,
  "executive-summary": `Executive Summary: Mid-Market Property Management Software Opportunity

Overview: Proceed with caution. The opportunity is real but commercially unvalidated. A genuine pain point exists in mid-market property management, where fragmented tools cost operators $3,500 per unit in tenant turnover and $718,560 per year in pipeline drag. The market is a $1.8B SAM growing at 11.3% CAGR. The competitive window is 18-24 months before AppFolio's AI capabilities narrow the gap. The decision is whether to fund the pilot phase conditional on securing 3 paid letters of intent within 90 days.

Strategic Fit: Customer demand alignment is moderate because 22 of 28 interviewed managers expressed willingness to pay $15-$25 per unit per month, but no binding commitments exist. Market structure fit is strong because mid-market fragmentation leaves room for entrants. Regulatory environment fit is strong because fair housing compliance and energy benchmarking create demand pull. Competitive positioning fit is moderate because the three-layer moat is defensible only if scale is reached within 18-24 months. Commercial dynamics fit is strong because $800-$2,400 monthly contract values support the target model. Technology and capability alignment is strong, while talent alignment is moderate because the company has 2 of the 4 AI or ML engineers it needs.

Cross-Chapter Synthesis: Opportunity Validation shows a real, quantified pain point with strong directional demand signals but zero commercial validation. Market Research shows a $1.8B SAM growing at 11.3% with fragmentation in the mid-market. Competitive Analysis shows an 18-24 month window before AppFolio's AI investments harden the market. Across all three chapters, the largest risk is commercial validation rather than structural demand.

Key Takeaways: The opportunity addresses a genuine $3,500 per unit pain point in a growing market with structural tailwinds. Commercial validation is the critical de-risk step because no binding commitments exist. The 18-24 month competitive window is real but closing. The three-layer moat of predictive algorithms, integration depth, and contractor network effects is defensible only with fast execution. Recommendation: proceed to pilot phase conditional on 3 paid LOIs within 90 days.

Risks and Next Steps: Risk 1: no commercial validation exists, probability high, severity high. Mitigation: secure 3 paid LOIs within 90 days. Risk 2: AppFolio's AI acquisition accelerates the competitive timeline, probability medium, severity high. Mitigation: focus on building predictive data advantage with early customers. Risk 3: customer acquisition costs exceed the $4,500 per account target, probability medium, severity medium. Mitigation: establish property management association partnerships. Risk 4: integration complexity delays time to market, probability low, severity high. Mitigation: prioritise a QuickBooks connector for launch and defer Sage.`,
};
