export const VISUAL_SAMPLE_TEXTS: Record<string, string> = {
  "opportunity-validation": `Opportunity Validation: Mid-Market Property Management Software

Overview: The core opportunity targets mid-market commercial property managers (50-500 units) who lack integrated software for tenant screening, lease management, and maintenance coordination. These managers juggle 3-4 separate tools, leading to data silos, missed renewal windows, and slow maintenance response times averaging 72 hours. Revenue shortfall from tenant turnover averages $3,500 per unit. The pipeline drag from manual processes costs an estimated $718,560 annually across a typical 200-unit portfolio. Queue attrition rate sits at 15% due to delayed maintenance responses. The urgency window is 18-24 months before AppFolio's AI capabilities close the differentiation gap.

Problem and Customer Definition: Regional property management companies with $5M-$50M in assets under management face a revenue floor collapse. Before digital consolidation, average revenue per unit was $284/kW-year. Current fragmented tool approaches have driven this down to $140/kW-year. The core problem is fragmented operations creating invisible revenue leakage. The primary customer is the operations director at mid-market property firms. The key pain point is tenant turnover cost averaging $3,500 per unit. The trigger event is typically a failed maintenance request escalating to lease non-renewal. The business consequence is a 50% drop in per-unit revenue and accelerating churn.

Demand Signals: Search interest for "property management automation" increased 340% since 2023 (observed signal, confirmed). Three major industry conferences added dedicated PropTech tracks in 2024 (industry signal, confirmed). Direct conversations with 28 property managers: 22 expressed willingness to pay $15-25/unit/month (customer indication, confirmed). However, stated willingness to pay has not been validated through actual purchase commitments (commercial proof, missing). No signed letters of intent or pilot agreements exist yet (commitment, missing). The evidence chain shows strong early signals but a critical gap between stated intent and commercial commitment.

Current Solution and Market Gap: Spreadsheet-based tracking (used by 60% of target segment) solves basic record-keeping but fails at cross-functional visibility and predictive alerts. Yardi Voyager provides comprehensive features but fails at mid-market affordability and implementation simplicity. Cobbled SaaS stacks (AppFolio + separate maintenance tools) solve individual workflows but fail at data integration and predictive capabilities. The revenue gap analysis shows spreadsheet users losing $349,300/year in preventable turnover, Yardi users losing $180,000/year in overpayment and underutilisation, and SaaS stack users losing $245,000/year in integration friction.

Customer Fundamentals: The buying process involves: Operations Director identifies need (veto power: high, cares about operational efficiency), CFO approves budget (veto power: high, requires ROI demonstration over 6 months), IT Director reviews security (veto power: medium, cares about integration and data security). Budget cycles are annual with Q4 decision-making for January implementation. Typical evaluation window is 4-8 weeks. The 6-month ROI requirement is the primary gate.

Risks and Next Steps: Risk 1 — No commercial validation exists beyond stated interest (probability: high, severity: high). Mitigation: Secure 3 paid letters of intent within 90 days. Risk 2 — AppFolio could add predictive maintenance features within 12 months (probability: medium, severity: high). Mitigation: Accelerate differentiation through proprietary maintenance data models. Risk 3 — Budget freeze in target segment due to interest rate environment (probability: medium, severity: medium). Mitigation: Structure offering as cost-saving tool with guaranteed ROI timeline. Risk 4 — Integration complexity with legacy accounting systems underestimated (probability: low, severity: high). Mitigation: Build QuickBooks and Sage connectors as launch requirements. Risk 5 — Customer acquisition cost exceeds $4,500/account target (probability: medium, severity: medium). Mitigation: Partner with property management associations for channel access.

Key Takeaways: The opportunity addresses a genuine, quantified pain point ($3,500/unit turnover cost across a fragmented mid-market). Demand signals are directionally strong but commercially unvalidated. The 18-24 month competitive window is real but closing. Priority action is converting stated interest into binding commercial commitments before scaling.`,

  "market-research": `Market Research: US Commercial Property Management Software

Overview: The US commercial property management software market is a $4.2B market growing at 11.3% CAGR. The market is moderately concentrated with structural tailwinds from digital transformation and regulatory compliance. The main constraint is customer acquisition cost in a market where switching costs create inertia. The implication is that new entrants need a clear wedge into the mid-market segment where fragmentation creates openings.

Market Sizing & Structure: TAM is $4.2B — all commercial property management software in the US and Canada, including enterprise, mid-market, and small business segments. SAM is $1.8B — mid-market operators (50-500 units) in US and Canada, excluding enterprise and micro segments. SOM is $45M — realistic year 1-3 capture at 2.5% of SAM, based on sales capacity and product maturity assumptions. Geographic concentration is highest in Sun Belt states (Texas 18%, Florida 15%, Arizona 9%). Buyer concentration: top 20 property management firms control 25% of mid-market units. Market structure is fragmented in mid-market (no player above 12% share) vs concentrated at enterprise level (top 5 hold 55%).

Trends & Growth: AI-driven predictive maintenance adoption growing 28% annually (direction: up, opportunity, implication: core differentiator for new entrants). Regulatory requirements for energy efficiency reporting expanding (direction: up, opportunity, implication: compliance-driven demand creates urgency). Consolidation among mid-tier firms accelerating (direction: up, threat, implication: fewer but larger potential customers). Remote property management shift is permanent (direction: stable, opportunity, implication: digital-first solutions are table stakes not differentiators).

Value Chain & Competitive Structure: The value chain flows from Property Acquisition & Setup through Tenant Acquisition & Onboarding to Ongoing Management & Maintenance to Financial Reporting & Distribution. The highest-margin activities sit in Ongoing Management where recurring SaaS revenue models dominate. Tenant Acquisition is becoming commoditized. Financial Reporting is dominated by accounting integrations. The whitespace is in predictive operations connecting Ongoing Management to Financial Reporting with real-time analytics.

Buying Cycle & Commercial Dynamics: Adoption stage is early majority. Typical buyer motion is inbound-led evaluation. Buying cycle length is 3-6 months for mid-market. Main gating events are CFO sign-off above $1,000/month and IT security review. Common failure points are failed integration demos and inability to demonstrate ROI within 6 months. Purchase format is annual SaaS subscription. Unit spend is $800-$2,400/month. Portfolio spend is $15-25 per unit/month. Budget structure is OpEx. Pricing anchor is AppFolio at $1.50-3.00/unit/month. Premium pricing conditions require demonstrable predictive capabilities. Nice-to-have: advanced analytics. Must-have: lease management, maintenance ticketing, tenant communication.

Policy & Regulatory Environment: Fair housing compliance requirements are positive — software that automates compliant screening reduces legal risk. Energy benchmarking mandates expanding to more cities is positive — creates compliance-driven demand. Data privacy regulations affecting tenant information is negative — increases development burden. Local rent control variations is negative — increases configuration complexity.

Entry Conditions & Adoption Constraints: Integration with QuickBooks/Sage is critical — 70% of mid-market firms use one of these. Mobile-first maintenance workflow required — field teams need mobile access. Customer acquisition cost averages $4,500/account. Minimum viable feature set must include lease management, maintenance ticketing, and financial reporting. Data migration from legacy systems is the primary adoption friction point.

Risks and Next Steps: Risk 1 — Market growth concentrated in segments we can't reach initially (probability: medium, severity: medium). Risk 2 — Pricing pressure from AppFolio's low price point (probability: high, severity: medium). Risk 3 — Regulatory fragmentation increases development costs (probability: medium, severity: low). Risk 4 — Customer acquisition costs exceed budget at $4,500/account (probability: medium, severity: high). Risk 5 — Integration complexity delays time to market (probability: low, severity: high).

Key Takeaways: $1.8B SAM with 11.3% CAGR provides a large and growing addressable market. Mid-market fragmentation (no player above 12%) creates a genuine opening. Buying cycles are 3-6 months with CFO sign-off as primary gate. Integration requirements and customer acquisition costs are the main barriers to entry.`,

  "competitive-analysis": `Competitive Analysis: Mid-Market Property Management Software

Overview: The competitive field is structured in three tiers: enterprise incumbents (Yardi, MRI), mid-market specialists (AppFolio, Buildium), and vertical-focused startups (Latchel, Property Meld). The market is in a growth/displacement phase where competitors primarily win against manual processes rather than each other. The company occupies a potential sweet spot in predictive mid-market operations, but the window for establishing position is 18-24 months before AppFolio's AI capabilities mature. The key question is whether the company can build sufficient scale to defend its predictive maintenance moat before the market consolidates.

Competitive Landscape Overview: AppFolio has 28,000+ customers with 22% YoY growth. Business model is SaaS at $1.50-3.00/unit/month. Strength: modern UI, strong accounting integration, brand awareness. Weakness: limited predictive maintenance, one-size-fits-all approach. Threat to company: high. Buildium (owned by RealPage) serves 15,000+ customers. Business model is SaaS focused on small-to-mid residential. Strength: residential depth, RealPage distribution. Weakness: weak commercial features. Threat: moderate. Yardi Voyager holds 35% of enterprise market. Business model is enterprise SaaS at $5-15/unit/month. Strength: comprehensive features, market dominance. Weakness: complexity, cost, poor mid-market UX. Threat: low-medium (Breeze product has limited traction). Latchel focuses on maintenance-only. Strength: deep maintenance workflow. Weakness: narrow scope, small customer base. Threat: low (potential acquisition target). Property Meld is also maintenance-only. Strength: good mobile experience. Weakness: no lease or financial features. Threat: low.

Market Position & Share Dynamics: AppFolio holds approximately 12% of mid-market share and growing 3-4 percentage points annually. Buildium holds 8% but flat. Yardi Breeze holds 3% and growing slowly. Others collectively hold 77%. The growth is primarily displacing spreadsheet workflows, not stealing from other vendors. Geographic concentration: AppFolio strongest in West Coast, Buildium in Northeast, Yardi everywhere at enterprise level.

Defensibility & Moat Architecture: Predictive maintenance algorithms — potentially defensible, no one has it today, company can build with 12-18 months of operational data. Accounting integration depth — moderately defensible, AppFolio and Yardi have it today, company must invest heavily upfront. Contractor marketplace network effects — potentially strong moat, Latchel has a nascent version, company can build alongside core product. Brand recognition — not defensible short-term, AppFolio and Yardi dominate, company needs 3-5 years. Switching costs: data lock-in (historical maintenance and tenant records), workflow dependency (teams built processes around the tool), integration complexity (accounting system connections are painful to recreate), training investment (staff ramp-up time is 2-4 weeks).

Differentiation & Right to Win: Predictive maintenance capability — our position: unique in mid-market, matters because it's the core differentiator from AppFolio. Mid-market focus — our position: purpose-built, matters because enterprise tools are over-complex and over-priced. Integration depth with mid-market accounting — our position: must build, matters because it's the switching cost that retains customers. Mobile-first maintenance — our position: competitive, matters because field teams require mobile access. Price/value ratio — our position: competitive at $15-25/unit/month, matters because it's above AppFolio's floor but justified by predictive features.

Risk & Fragility: AppFolio adds AI/predictive features — triggered by their 2024 AI startup acquisition, consequence: eliminates core differentiator. Yardi Breeze improves UX — triggered by continued investment, consequence: credible mid-market competitor from dominant player. New entrant from adjacent category — triggered by maintenance platforms expanding scope, consequence: compressed timeline for establishing position. Customer concentration risk — triggered by losing one or two large early accounts, consequence: revenue and reference customer loss. Talent acquisition — triggered by AI/ML engineer shortage, consequence: inability to build predictive models.

Key Takeaways: The market is in a growth/displacement phase with genuine room for a differentiated entrant. AppFolio is the primary competitor but lacks predictive capabilities today. The 18-24 month window is real. The three-layer moat (predictive algorithms, integration depth, contractor network) is defensible if sufficient scale is achieved. Speed of execution matters more than feature breadth at this stage.

Risks and Next Steps: Risk 1 — AppFolio's AI acquisition accelerates predictive features (probability: medium, severity: high). Risk 2 — Customer acquisition costs exceed $4,500/account (probability: medium, severity: medium). Risk 3 — Integration complexity delays launch (probability: low, severity: high). Risk 4 — Early customer churn before moat is established (probability: medium, severity: high). Risk 5 — Talent shortage in AI/ML engineering (probability: high, severity: medium).`,

  "executive-summary": `Executive Summary: Mid-Market Property Management Software Opportunity

Overview: Proceed with caution — the opportunity is real but commercially unvalidated. A genuine pain point exists in mid-market property management (50-500 units) where fragmented tools cost operators $3,500/unit in tenant turnover and $718,560/year in pipeline drag. The market is $1.8B SAM growing at 11.3% CAGR with structural tailwinds. The competitive window is 18-24 months before AppFolio's AI capabilities close the gap. The reader needs to decide whether to fund the pilot phase conditional on securing 3 paid letters of intent within 90 days.

Strategic Fit: The strategic fit assessment shows alignment in most dimensions but a critical gap in commercial validation. Customer demand alignment: 22 of 28 interviewed managers expressed willingness to pay $15-25/unit/month, but no binding commitments exist — Moderate Fit. Market structure fit: mid-market fragmentation with no player above 12% share creates a genuine opening — Strong Fit. Regulatory environment alignment: fair housing compliance and energy benchmarking mandates create compliance-driven demand — Strong Fit. Competitive positioning: the three-layer moat (predictive, integration, contractor network) is defensible if scale is achieved within 18-24 months — Moderate Fit. Commercial dynamics fit: $800-2,400/month contract values with annual SaaS model match target unit economics — Strong Fit. Technology / capability alignment: predictive maintenance requires 12-18 months of operational data to train models, team has relevant ML expertise — Strong Fit. Talent alignment: AI/ML engineering is scarce, company has 2 of needed 4 engineers — Moderate Fit.

Cross-Chapter Synthesis: Opportunity Validation core finding is that the pain point is genuine and quantified at $3,500/unit, with strong directional demand signals but zero commercial validation. Confidence: medium. Key risk: no purchase commitments beyond stated interest. Market Research core finding is that $1.8B SAM growing 11.3% with fragmented mid-market creates structural opening. Confidence: high. Key risk: customer acquisition costs of $4,500/account may exceed budget. Competitive Analysis core finding is that 18-24 month window exists before AppFolio's AI capabilities mature, three-layer moat is defensible with scale. Confidence: medium. Key risk: AppFolio's 2024 AI acquisition could accelerate their timeline.

The three chapters converge on a consistent narrative: the opportunity is structurally sound but execution-dependent. The pain point is real, the market is growing, and the competitive window exists. The single biggest risk is not competitive — it's commercial. No amount of market analysis substitutes for actual purchase commitments. The strategic fit matrix shows 4 of 7 dimensions at Strong Fit, suggesting the opportunity merits continued investment, but the 3 Moderate Fit areas all relate to validation and execution rather than market fundamentals.

Key Takeaways: 1. Genuine $3,500/unit pain point in a $1.8B growing market with structural tailwinds. 2. Commercial validation is the critical de-risk step — strong signals exist but zero binding commitments. 3. The 18-24 month competitive window is real but closing as AppFolio invests in AI. 4. Three-layer moat (predictive algorithms, integration depth, contractor network) is defensible at scale. 5. Recommendation: proceed to pilot phase conditional on 3 paid LOIs within 90 days.

Risks and Next Steps: Risk 1 — No commercial validation exists (probability: high, severity: high). Mitigation: Secure 3 paid letters of intent within 90 days. Risk 2 — AppFolio AI acquisition accelerates competitive timeline (probability: medium, severity: high). Mitigation: Focus on building predictive data advantage with early customers. Risk 3 — Customer acquisition costs exceed $4,500/account budget (probability: medium, severity: medium). Mitigation: Establish property management association partnerships for channel access. Risk 4 — Integration complexity delays time to market (probability: low, severity: high). Mitigation: Prioritise QuickBooks connector as launch requirement, defer Sage.`,
};
